// Spanish, French, German, Chinese, Japanese, Arabic, Persian.
export default {
  'Getting started':['Primeros pasos','Premiers pas','Erste Schritte','开始使用','はじめに','البدء','شروع کار'],
  'Git history':['Historial de Git','Historique Git','Git-Verlauf','Git 历史','Git 履歴','سجل Git','تاریخچهٔ گیت'],
  'Inspecting buildings':['Inspeccionar edificios','Inspecter les bâtiments','Gebäude untersuchen','检查建筑','建物の調査','فحص المباني','بررسی ساختمان‌ها'],
  'Advanced tools':['Herramientas avanzadas','Outils avancés','Erweiterte Werkzeuge','高级工具','詳細ツール','أدوات متقدمة','ابزارهای پیشرفته'],
  'Navigation and tips':['Navegación y consejos','Navigation et conseils','Navigation und Tipps','导航与提示','操作とヒント','التنقل والنصائح','جابه‌جایی و نکته‌ها'],
  'Open a folder from Project → Open project. Browse folders, go to the parent folder, or paste a path. Source is scanned locally without running project code.':[
    'Abre una carpeta desde Proyecto → Abrir proyecto. Explora carpetas, sube a la carpeta superior o pega una ruta. El código se analiza localmente sin ejecutarlo.',
    'Ouvrez un dossier via Projet → Ouvrir un projet. Parcourez les dossiers, remontez au parent ou collez un chemin. Les sources sont analysées localement sans exécuter le code.',
    'Öffnen Sie einen Ordner über Projekt → Projekt öffnen. Durchsuchen Sie Ordner, wechseln Sie zum übergeordneten Ordner oder fügen Sie einen Pfad ein. Quellcode wird lokal analysiert und nicht ausgeführt.',
    '通过“项目 → 打开项目”选择文件夹。可以浏览文件夹、进入上级文件夹或粘贴路径。源码在本地扫描，不会执行项目代码。',
    '「プロジェクト → プロジェクトを開く」でフォルダーを選択します。フォルダーの参照、親フォルダーへの移動、パスの貼り付けができます。コードを実行せずローカルで解析します。',
    'افتح مجلدًا من المشروع ← فتح مشروع. تصفح المجلدات أو انتقل للمجلد الأب أو الصق مسارًا. يُفحص المصدر محليًا دون تشغيل شيفرة المشروع.',
    'از منوی «پروژه ← باز کردن پروژه» یک پوشه باز کنید. پوشه‌ها را مرور کنید، به پوشهٔ بالاتر بروید یا مسیر را وارد کنید. کد به‌صورت محلی و بدون اجرا بررسی می‌شود.',
  ],
  'Open recent reopens a saved folder. Close project clears the city. Exclusions hide files, folders, symbols, or path patterns; Apply rescans, and removing a rule restores them.':[
    'Recientes vuelve a abrir una carpeta guardada. Cerrar proyecto vacía la ciudad. Las exclusiones ocultan archivos, carpetas, símbolos o patrones; Aplicar vuelve a analizar y quitar una regla los restaura.',
    'Projets récents rouvre un dossier enregistré. Fermer le projet vide la ville. Les exclusions masquent fichiers, dossiers, symboles ou motifs de chemin ; Appliquer relance l’analyse, et retirer une règle les restaure.',
    'Zuletzt geöffnet öffnet gespeicherte Ordner erneut. Projekt schließen leert die Stadt. Ausschlüsse verbergen Dateien, Ordner, Symbole oder Pfadmuster; Anwenden analysiert erneut, entfernte Regeln stellen Elemente wieder her.',
    '“最近的项目”重新打开已保存的文件夹。“关闭项目”清空城市。排除规则可隐藏文件、文件夹、符号或路径模式；应用会重新扫描，移除规则可恢复内容。',
    '最近のプロジェクトから保存済みフォルダーを開けます。閉じると都市が空になります。除外でファイル、フォルダー、シンボル、パスを非表示にできます。適用で再解析し、規則を削除すると復元します。',
    'المشاريع الأخيرة تعيد فتح مجلد محفوظ. إغلاق المشروع يفرغ المدينة. الاستثناءات تخفي ملفات أو مجلدات أو رموزًا أو أنماط مسارات؛ التطبيق يعيد الفحص وإزالة القاعدة تستعيدها.',
    '«پروژه‌های اخیر» پوشهٔ ذخیره‌شده را دوباره باز می‌کند. «بستن پروژه» شهر را خالی می‌کند. استثناها فایل، پوشه، نماد یا الگوی مسیر را پنهان می‌کنند؛ «اعمال» بررسی را تکرار می‌کند و حذف قانون آن بخش را برمی‌گرداند.',
  ],
  'Simple mode includes metric mapping, saved defaults, Git history, building details, and source preview. Advanced adds search, district filtering, street controls, queries, and investigations. Your mode is remembered.':[
    'El modo simple incluye métricas, valores predeterminados, historial Git, detalles y vista del código. El avanzado añade búsqueda, filtro de distrito, calles, consultas e investigaciones. El modo se recuerda.',
    'Le mode simple propose métriques, valeurs par défaut, historique Git, détails et aperçu des sources. Le mode avancé ajoute recherche, filtre de quartier, rues, requêtes et investigations. Votre mode est mémorisé.',
    'Einfach enthält Metrikzuordnung, gespeicherte Vorgaben, Git-Verlauf, Gebäudedetails und Quellvorschau. Erweitert ergänzt Suche, Bezirksfilter, Straßensteuerung, Abfragen und Untersuchungen. Der Modus wird gespeichert.',
    '简洁模式提供指标映射、默认设置、Git 历史、建筑详情和源码预览。高级模式增加搜索、区域筛选、街道控制、查询和调查。模式选择会被记住。',
    'シンプルモードには指標設定、既定値の保存、Git 履歴、建物の詳細、ソースのプレビューがあります。詳細モードは検索、地区フィルター、道路設定、クエリ、調査を追加します。選択は保存されます。',
    'الوضع البسيط يشمل تعيين المقاييس والإعدادات المحفوظة وسجل Git وتفاصيل المباني ومعاينة المصدر. المتقدم يضيف البحث وتصفية الأحياء والشوارع والاستعلامات والفحص. يُحفظ اختيار الوضع.',
    'حالت ساده شامل تنظیم معیارها، پیش‌فرض ذخیره‌شده، تاریخچهٔ گیت، جزئیات ساختمان و پیش‌نمایش کد است. حالت پیشرفته جست‌وجو، فیلتر ناحیه، کنترل خیابان‌ها، پرس‌وجو و بررسی را اضافه می‌کند. حالت انتخابی حفظ می‌شود.',
  ],
  'Height controls how tall buildings are; footprint controls their ground area; colour controls their surface tint. Change each independently and check the legend for the current meaning.':[
    'Altura controla lo alto de los edificios; superficie controla su área en el suelo; color controla su tono. Cambia cada dimensión por separado y consulta la leyenda.',
    'La hauteur règle la taille verticale ; l’emprise règle la surface au sol ; la couleur règle la teinte. Modifiez chaque dimension séparément et consultez la légende.',
    'Höhe steuert die Gebäudehöhe, Grundfläche die Fläche am Boden und Farbe die Tönung. Ändern Sie jede Dimension unabhängig und prüfen Sie die Legende.',
    '高度控制建筑有多高，占地面积控制地面面积，颜色控制表面色调。三者可以独立修改，请查看图例确认当前含义。',
    '高さは建物の高さ、底面積は地面の面積、色は表面の色を設定します。それぞれ独立して変更でき、現在の意味は凡例で確認できます。',
    'الارتفاع يحدد طول المباني، والمساحة تحدد مساحة قاعدتها، واللون يحدد لون السطح. غيّر كل بُعد مستقلاً وراجع دليل الألوان لمعناه الحالي.',
    'ارتفاع، بلندی ساختمان را تعیین می‌کند؛ مساحت پایه، فضای روی زمین را؛ و رنگ، رنگ سطح را. هرکدام را مستقل تغییر دهید و معنی فعلی را در راهنمای رنگ و اندازه ببینید.',
  ],
  'NOM counts methods; NOA counts attributes; LOC counts source lines. Dependencies measures connected links. Select a metric value in building details to inspect its evidence in Advanced mode.':[
    'NOM cuenta métodos; NOA atributos; LOC líneas de código. Dependencias mide los enlaces conectados. Selecciona un valor en los detalles para ver su evidencia en modo avanzado.',
    'NOM compte les méthodes, NOA les attributs, LOC les lignes de source. Dépendances mesure les liens connectés. Cliquez sur une valeur dans les détails pour examiner ses preuves en mode avancé.',
    'NOM zählt Methoden, NOA Attribute, LOC Quellzeilen. Abhängigkeiten misst verbundene Verknüpfungen. Wählen Sie einen Metrikwert in den Gebäudedetails, um im erweiterten Modus die Belege zu prüfen.',
    'NOM 是方法数，NOA 是属性数，LOC 是源码行数。依赖衡量关联链接。点击建筑详情中的指标值，可在高级模式查看计算依据。',
    'NOM はメソッド数、NOA は属性数、LOC はソース行数です。依存は接続リンクを表します。建物の詳細で値を選ぶと、詳細モードで根拠を確認できます。',
    'NOM عدد الأساليب، وNOA عدد الخصائص، وLOC أسطر المصدر. التبعيات تقيس الروابط المتصلة. اختر قيمة في تفاصيل المبنى لفحص دليلها في الوضع المتقدم.',
    'NOM تعداد متدها، NOA تعداد ویژگی‌ها و LOC تعداد خطوط کد است. وابستگی‌ها پیوندهای متصل را می‌سنجند. روی مقدار معیار در جزئیات ساختمان کلیک کنید تا شواهد آن را در حالت پیشرفته ببینید.',
  ],
  'Boxplot groups sizes into five categories using this project’s quartiles and whiskers. Threshold uses fixed bands. Linear varies sizes continuously with compressed height so large buildings remain readable.':[
    'Cuartiles agrupa tamaños en cinco categorías según los cuartiles y bigotes del proyecto. Umbral usa bandas fijas. Lineal varía los tamaños continuamente y comprime la altura para mantener la legibilidad.',
    'Quartiles classe les tailles en cinq catégories selon les quartiles et moustaches du projet. Seuil utilise des bandes fixes. Linéaire fait varier les tailles en continu, avec une hauteur comprimée pour rester lisible.',
    'Boxplot ordnet Größen anhand der Quartile und Whisker des Projekts in fünf Kategorien. Schwellenwerte verwenden feste Bereiche. Linear variiert Größen kontinuierlich mit komprimierter Höhe für bessere Lesbarkeit.',
    '箱线图按项目的四分位数和须线将大小分为五类。阈值使用固定区间。线性模式连续改变大小，并压缩高度以保持大型建筑的可读性。',
    '箱ひげ図はプロジェクトの四分位数とひげでサイズを5段階に分けます。しきい値は固定区間を使います。線形は連続的に変化し、高さを圧縮して大きな建物も見やすくします。',
    'المخطط الصندوقي يقسم الأحجام إلى خمس فئات بحسب أرباع المشروع وحدوده. العتبة تستخدم نطاقات ثابتة. الخطي يغيّر الأحجام باستمرار مع ضغط الارتفاع لتظل المباني الكبيرة مقروءة.',
    'نمودار جعبه‌ای اندازه‌ها را با چارک‌ها و حدود همین پروژه در پنج گروه قرار می‌دهد. آستانه از بازه‌های ثابت استفاده می‌کند. حالت خطی اندازه را پیوسته تغییر می‌دهد و ارتفاع را فشرده می‌کند تا ساختمان‌های بزرگ خوانا بمانند.',
  ],
  'Language assigns a distinct colour to each language. Coverage uses red for low and green for high coverage; grey means unknown. Import a file coverage JSON report under Advanced investigations.':[
    'Idioma asigna un color a cada lenguaje. Cobertura usa rojo para valores bajos y verde para altos; gris significa desconocido. Importa un informe JSON por archivo en Investigaciones avanzadas.',
    'Langue attribue une couleur à chaque langage. Couverture utilise le rouge pour les faibles valeurs, le vert pour les fortes ; gris signifie inconnu. Importez un rapport JSON par fichier dans les investigations avancées.',
    'Sprache gibt jeder Sprache eine eigene Farbe. Testabdeckung zeigt niedrige Werte rot und hohe grün; Grau bedeutet unbekannt. Importieren Sie einen JSON-Bericht pro Datei unter erweiterten Untersuchungen.',
    '语言为每种语言分配不同颜色。覆盖率用红色表示低覆盖、绿色表示高覆盖；灰色表示未知。可在高级调查中导入文件覆盖率 JSON 报告。',
    '言語は各言語に異なる色を割り当てます。カバレッジは低いと赤、高いと緑、未取得は灰色です。詳細モードの調査からファイル別の JSON レポートを読み込めます。',
    'اللغة تخصص لونًا لكل لغة. التغطية حمراء للقيم المنخفضة وخضراء للمرتفعة؛ الرمادي يعني غير معروف. استورد تقرير تغطية الملفات بصيغة JSON في الفحص المتقدم.',
    'گزینهٔ زبان به هر زبان رنگ جدا می‌دهد. پوشش آزمون برای مقدار کم قرمز و برای مقدار زیاد سبز است؛ خاکستری یعنی نامشخص. گزارش پوشش فایل‌ها با قالب JSON را در بخش بررسیِ حالت پیشرفته وارد کنید.',
  ],
  'Save as default writes height, footprint, colour, and mapping to your user profile. The saved mapping loads on the next app launch for any project. Unsaved changes affect this session.':[
    'Guardar como predeterminado escribe altura, superficie, color y escala en tu perfil. Se cargan al iniciar de nuevo para cualquier proyecto. Los cambios sin guardar solo afectan a esta sesión.',
    'Enregistrer par défaut écrit hauteur, emprise, couleur et échelle dans votre profil. Ces réglages sont chargés au prochain lancement pour tous les projets. Les modifications non enregistrées restent dans cette session.',
    'Als Standard speichern schreibt Höhe, Grundfläche, Farbe und Skalierung ins Benutzerprofil. Beim nächsten Start gelten sie für jedes Projekt. Ungespeicherte Änderungen gelten nur für diese Sitzung.',
    '“保存为默认”将高度、占地面积、颜色和映射写入用户配置。下次启动时会为所有项目加载这些设置。未保存的修改只影响本次会话。',
    '「既定値として保存」は高さ、底面積、色、尺度をユーザープロファイルに保存します。次の起動時にすべてのプロジェクトで読み込まれます。未保存の変更は今回のセッションに適用されます。',
    'الحفظ كإعداد افتراضي يكتب الارتفاع والمساحة واللون والتدرج في ملفك الشخصي. تُحمّل عند التشغيل التالي لأي مشروع. التغييرات غير المحفوظة تخص هذه الجلسة.',
    '«ذخیره به‌عنوان پیش‌فرض» ارتفاع، مساحت پایه، رنگ و مقیاس را در فایل تنظیمات کاربر می‌نویسد. در اجرای بعدی برنامه برای هر پروژه بارگذاری می‌شود. تغییرات ذخیره‌نشده فقط مربوط به این نشست‌اند.',
  ],
  'Build history and ▶ play commits from oldest to newest; ⏸ pauses. Drag the timeline to inspect a commit. The last position restores the current model, including uncommitted files.':[
    'Construir historial y ▶ reproducen los commits del más antiguo al más reciente; ⏸ pausa. Arrastra la línea temporal para inspeccionar un commit. La última posición restaura el modelo actual y los archivos sin commit.',
    'Construire l’historique et ▶ parcourent les commits du plus ancien au plus récent ; ⏸ met en pause. Déplacez le curseur pour examiner un commit. La dernière position restaure le modèle actuel, fichiers non validés inclus.',
    'Verlauf aufbauen und ▶ spielen Commits vom ältesten zum neuesten ab; ⏸ pausiert. Ziehen Sie die Zeitleiste zu einem Commit. Die letzte Position stellt das aktuelle Modell samt uncommitteten Dateien wieder her.',
    '“构建历史”和 ▶ 从旧到新播放提交；⏸ 暂停。拖动时间轴可查看某次提交。最后一个位置恢复当前模型，包括未提交的文件。',
    '履歴の構築と ▶ で古いコミットから順に再生し、⏸ で一時停止します。スライダーでコミットを選べます。最後の位置では未コミットのファイルを含む現在のモデルに戻ります。',
    'بناء السجل و▶ يعرضان الالتزامات من الأقدم للأحدث؛ ⏸ يوقف مؤقتًا. حرّك الخط الزمني لفحص التزام. الموضع الأخير يعيد النموذج الحالي بما فيه الملفات غير الملتزم بها.',
    '«ساخت تاریخچه» و ▶ ثبت‌های گیت را از قدیمی به جدید پخش می‌کنند؛ ⏸ مکث می‌کند. نوار زمان را برای بررسی یک ثبت بکشید. آخرین جایگاه مدل فعلی، شامل فایل‌های ثبت‌نشده، را برمی‌گرداند.',
  ],
  'Approximate growth estimates past sizes from file lines. Commit structure parses source at each commit. Compare with current shows additions, changes, and removed buildings. Git commits are required.':[
    'Crecimiento aproximado estima tamaños anteriores por las líneas de archivo. Estructura del commit analiza el código de cada commit. Comparar con actual muestra edificios añadidos, cambiados y eliminados. Requiere commits de Git.',
    'Croissance approximative estime les tailles passées à partir des lignes des fichiers. Structure du commit analyse les sources de chaque commit. Comparer avec l’actuel affiche ajouts, changements et suppressions. Des commits Git sont nécessaires.',
    'Ungefähres Wachstum schätzt frühere Größen aus Dateizeilen. Commit-Struktur analysiert den Quellcode jedes Commits. Mit aktuell vergleichen zeigt neue, geänderte und entfernte Gebäude. Git-Commits sind erforderlich.',
    '近似增长通过文件行数估算过去大小。提交结构解析每次提交的源码。与当前比较可显示新增、修改和删除的建筑。需要 Git 提交记录。',
    '概算の成長はファイル行数から過去の大きさを推定します。コミット構造は各時点のソースを解析します。現在と比較すると追加、変更、削除された建物が分かります。Git コミットが必要です。',
    'النمو التقريبي يقدّر الأحجام الماضية من أسطر الملفات. بنية الالتزام تحلل المصدر لكل التزام. المقارنة بالحالي تظهر المباني المضافة والمعدلة والمحذوفة. يلزم سجل التزامات Git.',
    'رشد تقریبی اندازه‌های گذشته را از تعداد خطوط فایل تخمین می‌زند. ساختار ثبت، کد هر ثبت گیت را تحلیل می‌کند. مقایسه با وضعیت فعلی ساختمان‌های اضافه‌شده، تغییرکرده و حذف‌شده را نشان می‌دهد. وجود ثبت گیت لازم است.',
  ],
  'Click a building or select it from the building list. Preview source shows its lines; copy path copies its location; Open in file manager reveals the source file.':[
    'Haz clic en un edificio o elígelo de la lista. Vista del código muestra sus líneas; copiar ruta copia su ubicación; Abrir en explorador localiza el archivo fuente.',
    'Cliquez sur un bâtiment ou choisissez-le dans la liste. Aperçu des sources affiche ses lignes ; copier le chemin copie son emplacement ; le gestionnaire de fichiers révèle le fichier source.',
    'Klicken Sie auf ein Gebäude oder wählen Sie es aus der Liste. Quellvorschau zeigt Zeilen, Pfad kopieren kopiert den Speicherort, und im Dateimanager öffnen zeigt die Quelldatei.',
    '点击建筑或从建筑列表选择。源码预览显示相关行；复制路径复制位置；在文件管理器中打开可定位源文件。',
    '建物をクリックするか一覧から選択します。ソースのプレビューで行を表示し、パスをコピーで場所をコピーし、ファイルマネージャーでソースファイルを確認できます。',
    'انقر مبنى أو اختره من القائمة. معاينة المصدر تعرض أسطره، ونسخ المسار ينسخ موقعه، وفتح مدير الملفات يظهر ملف المصدر.',
    'روی ساختمان کلیک کنید یا آن را از فهرست ساختمان‌ها انتخاب کنید. پیش‌نمایش کد خطوط آن را نشان می‌دهد؛ کپی مسیر، نشانی فایل را کپی می‌کند؛ و باز کردن در مدیر فایل، فایل منبع را نمایش می‌دهد.',
  ],
  'Advanced details include metric evidence, members, incoming and outgoing links, and cycles. Select a member to preview its lines. Editor link settings accepts {path}, {line}, and {end} placeholders.':[
    'Los detalles avanzados incluyen evidencia, miembros, enlaces entrantes y salientes, y ciclos. Selecciona un miembro para ver sus líneas. El enlace al editor acepta {path}, {line} y {end}.',
    'Les détails avancés incluent preuves des métriques, membres, liens entrants et sortants et cycles. Choisissez un membre pour voir ses lignes. Le lien éditeur accepte {path}, {line} et {end}.',
    'Erweiterte Details enthalten Metrikbelege, Mitglieder, eingehende und ausgehende Links und Zyklen. Wählen Sie ein Mitglied für seine Quellzeilen. Editorlinks unterstützen {path}, {line} und {end}.',
    '高级详情包含指标依据、成员、传入和传出链接、循环。选择成员可预览其源码行。编辑器链接设置支持 {path}、{line} 和 {end} 占位符。',
    '詳細には指標の根拠、メンバー、入出力リンク、循環があります。メンバーを選ぶと該当行を表示します。エディターのリンク設定では {path}、{line}、{end} を使用できます。',
    'التفاصيل المتقدمة تشمل أدلة المقاييس والأعضاء والروابط الداخلة والخارجة والدورات. اختر عضوًا لمعاينة أسطره. رابط المحرر يقبل {path} و{line} و{end}.',
    'جزئیات پیشرفته شامل شواهد معیار، اعضا، پیوندهای ورودی و خروجی و چرخه‌هاست. عضو را انتخاب کنید تا خطوطش دیده شود. تنظیم پیوند ویرایشگر جای‌نگهدارهای {path}، {line} و {end} را می‌پذیرد.',
  ],
  'Search finds a class or file and moves the camera to it. District limits the view to one folder. Streets can show all links, only the selected building’s links, or none.':[
    'Buscar encuentra una clase o archivo y mueve la cámara. Distrito limita la vista a una carpeta. Calles muestra todos los enlaces, solo los del edificio seleccionado o ninguno.',
    'Recherche trouve une classe ou un fichier et y déplace la caméra. Quartier limite la vue à un dossier. Rues affiche tous les liens, ceux du bâtiment sélectionné ou aucun.',
    'Suche findet Klassen oder Dateien und bewegt die Kamera dorthin. Bezirk begrenzt die Ansicht auf einen Ordner. Straßen zeigt alle Links, nur die des gewählten Gebäudes oder keine.',
    '搜索找到类或文件并将相机移到那里。区域将视图限制到一个文件夹。街道可显示所有链接、仅选中建筑的链接或不显示。',
    '検索でクラスやファイルを探してカメラを移動します。地区でフォルダーを絞ります。道路はすべて、選択した建物のみ、非表示から選べます。',
    'البحث يجد صنفًا أو ملفًا وينقل الكاميرا إليه. الحي يحصر العرض بمجلد واحد. الشوارع تعرض كل الروابط أو روابط المبنى المحدد فقط أو لا شيء.',
    'جست‌وجو کلاس یا فایل را پیدا می‌کند و دوربین را به آن می‌برد. ناحیه، نمایش را به یک پوشه محدود می‌کند. خیابان‌ها می‌توانند همهٔ پیوندها، فقط پیوندهای ساختمان انتخابی یا هیچ‌کدام را نشان دهند.',
  ],
  'Queries tag matching buildings and dim the rest. Combine filters such as loc>200, type:class, and lang:ts. Run applies the query, clear removes it, and save stores a named query.':[
    'Las consultas marcan edificios coincidentes y atenúan el resto. Combina loc>200, type:class y lang:ts. Ejecutar aplica, limpiar elimina y guardar almacena una consulta con nombre.',
    'Les requêtes marquent les bâtiments correspondants et atténuent les autres. Combinez loc>200, type:class et lang:ts. Exécuter applique, effacer annule, enregistrer conserve une requête nommée.',
    'Abfragen markieren passende Gebäude und dimmen die anderen. Kombinieren Sie loc>200, type:class und lang:ts. Ausführen wendet an, Löschen entfernt, Speichern sichert eine benannte Abfrage.',
    '查询标记匹配建筑并淡化其余建筑。可以组合 loc>200、type:class 和 lang:ts。运行应用查询，清除移除查询，保存存储命名查询。',
    'クエリは一致した建物を強調し、他を薄くします。loc>200、type:class、lang:ts を組み合わせられます。実行で適用、クリアで解除、保存で名前付きクエリを保存します。',
    'الاستعلامات تميز المباني المطابقة وتخفف البقية. اجمع loc>200 وtype:class وlang:ts. تشغيل يطبق، ومسح يلغي، وحفظ يخزن استعلامًا باسم.',
    'پرس‌وجو ساختمان‌های مطابق را علامت می‌زند و بقیه را کم‌رنگ می‌کند. فیلترهایی مثل loc>200، type:class و lang:ts را ترکیب کنید. اجرا اعمال می‌کند، پاک کردن حذف می‌کند و ذخیره یک پرس‌وجوی نام‌دار نگه می‌دارد.',
  ],
  'Investigations rank review candidates by size, coupling, complexity, churn, or coverage. Generated code is excluded. Use sorting to explore results; select a minimap building to inspect it.':[
    'Las investigaciones ordenan candidatos por tamaño, acoplamiento, complejidad, cambios o cobertura. Se excluye código generado. Ordena los resultados y selecciona edificios en el minimapa.',
    'Les investigations classent les candidats par taille, couplage, complexité, changements ou couverture. Le code généré est exclu. Triez les résultats ou sélectionnez un bâtiment sur la minicarte.',
    'Untersuchungen sortieren Prüfkandidaten nach Größe, Kopplung, Komplexität, Änderungen oder Testabdeckung. Generierter Code ist ausgeschlossen. Sortieren Sie Ergebnisse oder wählen Sie ein Gebäude in der Minikarte.',
    '调查按大小、耦合、复杂度、变更或覆盖率排列候选项，排除生成代码。通过排序探索结果；选择小地图中的建筑可查看详情。',
    '調査はサイズ、結合、複雑度、変更頻度、カバレッジで候補を順位付けし、生成コードを除きます。並べ替えで結果を確認し、ミニマップの建物を選んで調査できます。',
    'الفحص يرتب المرشحين بحسب الحجم أو الترابط أو التعقيد أو التغييرات أو التغطية. تُستبعد الشيفرة المولدة. رتّب النتائج واختر مبنى من الخريطة المصغرة لفحصه.',
    'بررسی، موارد پیشنهادی را بر اساس اندازه، وابستگی، پیچیدگی، تغییرات یا پوشش مرتب می‌کند. کد تولیدشده کنار گذاشته می‌شود. نتایج را مرتب کنید؛ برای بررسی روی ساختمان نقشهٔ کوچک کلیک کنید.',
  ],
  'Drag to orbit, wheel to zoom, and right-drag to pan. [ and ] select previous and next buildings. ⌂ resets the view, ☰ opens the building list, and ? opens help. Escape closes help.':[
    'Arrastra para orbitar, rueda para acercar y arrastre derecho para desplazar. [ y ] seleccionan edificios. ⌂ restablece, ☰ abre la lista y ? la ayuda. Escape cierra la ayuda.',
    'Glissez pour tourner, molette pour zoomer, bouton droit pour déplacer. [ et ] sélectionnent les bâtiments. ⌂ réinitialise, ☰ ouvre la liste, ? ouvre l’aide. Échap ferme l’aide.',
    'Ziehen dreht, Mausrad zoomt, Rechtsziehen verschiebt. [ und ] wählen vorherige und nächste Gebäude. ⌂ setzt zurück, ☰ öffnet die Liste, ? die Hilfe. Escape schließt die Hilfe.',
    '拖动旋转，滚轮缩放，右键拖动平移。[ 和 ] 选择上一个和下一个建筑。⌂ 重置视图，☰ 打开建筑列表，? 打开帮助。Escape 关闭帮助。',
    'ドラッグで回転、ホイールで拡大縮小、右ドラッグで移動します。[ と ] で前後の建物を選択。⌂ でリセット、☰ で一覧、? でヘルプを開き、Escape で閉じます。',
    'اسحب للدوران واستخدم العجلة للتكبير والسحب الأيمن للتحريك. [ و] يحددان المباني السابقة والتالية. ⌂ يعيد العرض، ☰ يفتح القائمة، ? يفتح المساعدة. Escape يغلقها.',
    'کشیدن برای چرخش، چرخ ماوس برای بزرگ‌نمایی و کشیدن با دکمهٔ راست برای جابه‌جایی است. [ و ] ساختمان قبلی و بعدی را انتخاب می‌کنند. ⌂ نما را بازنشانی، ☰ فهرست و ? راهنما را باز می‌کند. Escape راهنما را می‌بندد.',
  ],
  'Panel headers fold or expand controls. Auto-hide folds idle panels in Advanced mode. Pause motion stops ambient animation; pause Git playback separately. Auto-orbit rotates the camera.':[
    'Las cabeceras pliegan o expanden paneles. Ocultar automáticamente pliega paneles inactivos en avanzado. Pausar movimiento detiene la animación ambiental; pausa Git por separado. Órbita automática gira la cámara.',
    'Les en-têtes replient ou déplient les panneaux. Masquage auto replie les panneaux inactifs en mode avancé. Pause des animations arrête le décor ; mettez Git en pause séparément. Rotation auto tourne la caméra.',
    'Panelkopfzeilen klappen die Steuerung ein oder aus. Automatisches Ausblenden klappt inaktive Panels im erweiterten Modus ein. Bewegung pausieren stoppt Umgebungsanimation; Git-Wiedergabe separat pausieren. Automatischer Rundflug dreht die Kamera.',
    '面板标题可折叠或展开控件。自动隐藏在高级模式折叠闲置面板。暂停动画停止环境动画；Git 播放需单独暂停。自动环绕旋转相机。',
    '見出しでパネルを折り畳めます。自動非表示は詳細モードで未操作のパネルを畳みます。アニメーション停止は背景を止めます。Git は別に停止してください。自動回転はカメラを回します。',
    'عناوين اللوحات تطوي الأدوات أو توسعها. الإخفاء التلقائي يطوي اللوحات الخاملة في الوضع المتقدم. إيقاف الحركة يوقف الزينة؛ أوقف عرض Git منفصلاً. الدوران التلقائي يدير الكاميرا.',
    'عنوان پنل، کنترل‌ها را جمع یا باز می‌کند. پنهان‌سازی خودکار پنل‌های بیکار را در حالت پیشرفته جمع می‌کند. توقف حرکت، پویانمایی محیط را متوقف می‌کند؛ پخش گیت را جداگانه متوقف کنید. چرخش خودکار دوربین را می‌چرخاند.',
  ],
  'Compare similar classes inside a district, then confirm outliers in source and tests. Some dependency links cannot be drawn as streets; inspect the link list. Estimates and missing links limit conclusions.':[
    'Compara clases similares de un distrito y confirma anomalías en código y pruebas. Algunos enlaces no se pueden dibujar como calles; consulta la lista. Las estimaciones y enlaces ausentes limitan las conclusiones.',
    'Comparez des classes similaires d’un quartier, puis vérifiez les anomalies dans les sources et tests. Certains liens ne peuvent être tracés en rues ; consultez leur liste. Estimations et liens absents limitent les conclusions.',
    'Vergleichen Sie ähnliche Klassen im Bezirk und prüfen Sie Auffälligkeiten in Quellcode und Tests. Manche Links können nicht als Straßen gezeichnet werden; prüfen Sie die Liste. Schätzungen und fehlende Links begrenzen Aussagen.',
    '比较区域内的相似类，再通过源码和测试确认异常。有些依赖无法绘制为街道，请检查链接列表。估算和缺失链接限制了结论。',
    '同じ地区の似たクラスを比較し、突出したものをソースとテストで確認します。道路に描けない依存もあるので一覧を確認してください。推定や欠落したリンクには限界があります。',
    'قارن أصنافًا متشابهة داخل الحي ثم تحقق من الشواذ في المصدر والاختبارات. بعض الروابط لا تُرسم كشوارع؛ راجع قائمة الروابط. التقديرات والروابط المفقودة تحد من الاستنتاجات.',
    'کلاس‌های مشابه در یک ناحیه را مقایسه کنید و سپس موارد نامتناسب را در کد و تست‌ها بررسی کنید. بعضی وابستگی‌ها به شکل خیابان رسم نمی‌شوند؛ فهرست پیوندها را ببینید. تخمین‌ها و پیوندهای مفقود نتیجه‌گیری را محدود می‌کنند.',
  ],
};
