export default {
  'Dependency map':['Mapa de dependencias','Carte des dépendances','Abhängigkeitskarte','依赖图','依存関係マップ','خريطة الاعتماديات','نقشهٔ وابستگی‌ها'],
  'Both directions':['Ambas direcciones','Deux directions','Beide Richtungen','双向','双方向','الاتجاهان','دوطرفه'],
  'Relationships':['Relaciones','Relations','Beziehungen','关系','関連','العلاقات','ارتباط‌ها'],
  'Ground streets':['Calles terrestres','Rues au sol','Bodenstraßen','地面街道','地上の道路','الشوارع الأرضية','خیابان‌های زمینی'],
  'Highlight related buildings':['Resaltar edificios relacionados','Éclairer les bâtiments liés','Verbundene Gebäude hervorheben','高亮相关建筑','関連する建物を強調','إبراز المباني المرتبطة','روشن کردن ساختمان‌های مرتبط'],
  'Select a node to explore its connections.':['Selecciona un nodo para explorar sus conexiones.','Sélectionnez un nœud pour explorer ses connexions.','Knoten auswählen, um Verbindungen zu erkunden.','选择节点查看其连接。','ノードを選択して接続を確認します。','اختر عقدة لاستكشاف روابطها.','برای بررسی ارتباط‌ها، یک گره را انتخاب کنید.'],
  'Self connections: {n}':['Conexiones consigo mismo: {n}','Connexions internes : {n}','Selbstverbindungen: {n}','自连接：{n}','自己接続：{n}','روابط ذاتية: {n}','ارتباط با خودش: {n}'],
  'Select a building to highlight its neighbors and explore the dependency map.':['Selecciona un edificio para resaltar sus vecinos y explorar el mapa de dependencias.','Sélectionnez un bâtiment pour éclairer ses voisins et explorer la carte des dépendances.','Ein Gebäude auswählen, um Nachbarn hervorzuheben und die Abhängigkeitskarte zu erkunden.','选择建筑以高亮邻居并查看依赖图。','建物を選択して関連する建物と依存関係マップを確認します。','اختر مبنى لإبراز جيرانه واستكشاف خريطة الاعتماديات.','یک ساختمان را انتخاب کنید تا همسایه‌های مرتبط روشن شوند و نقشهٔ وابستگی‌ها را بررسی کنید.'],
  'Ground routing is unavailable. Connections remain available in the dependency map.':['Las rutas terrestres no están disponibles. Las conexiones siguen en el mapa de dependencias.','Le tracé au sol est indisponible. Les connexions restent dans la carte des dépendances.','Bodenrouten sind nicht verfügbar. Verbindungen bleiben in der Abhängigkeitskarte verfügbar.','地面路径不可用。连接仍可在依赖图中查看。','地上経路は利用できません。接続は依存関係マップで確認できます。','المسارات الأرضية غير متاحة. تبقى الروابط متاحة في خريطة الاعتماديات.','مسیر زمینی در دسترس نیست. ارتباط‌ها همچنان در نقشهٔ وابستگی‌ها قابل بررسی‌اند.'],
  'Related buildings glow briefly on selection. Blue is incoming, amber is outgoing, and purple is both directions. Pause animations and reduced motion disable the pulse.':['Los edificios relacionados brillan brevemente al seleccionar. Azul: entrante; ámbar: saliente; morado: ambas direcciones. Pausar animaciones y reducir movimiento desactivan el pulso.','Les bâtiments liés s’éclairent brièvement à la sélection. Bleu : entrant ; ambre : sortant ; violet : deux directions. La pause et le mouvement réduit désactivent la pulsation.','Verbundene Gebäude leuchten bei Auswahl kurz. Blau: eingehend; Gelb: ausgehend; Violett: beide Richtungen. Animationspause und reduzierte Bewegung deaktivieren den Impuls.','选择时相关建筑短暂发光。蓝色表示传入，琥珀色表示传出，紫色表示双向。暂停动画或减少动态效果会禁用脉冲。','選択時に関連する建物が短く光ります。青は入力、黄は出力、紫は双方向です。アニメーション停止や動きを減らす設定で点滅を無効にします。','تضيء المباني المرتبطة لفترة وجيزة عند التحديد. الأزرق وارد، والكهرماني صادر، والبنفسجي للاتجاهين. يوقف إيقاف الرسوم وتقليل الحركة النبضة.','هنگام انتخاب، ساختمان‌های مرتبط یک پالس کوتاه نور می‌گیرند. آبی ورودی، زرد خروجی و بنفش دوطرفه است. توقف حرکت و تنظیم کاهش حرکت، پالس را غیرفعال می‌کنند.'],
};
